{{- if and .Values.backups.enabled (eq .Values.backups.provider "s3") .Values.backups.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  {{- if empty .Values.backups.secret.name }}
  name: {{ include "cluster.fullname" . }}-backup-s3-creds
  {{- else }}
  name: {{ .Values.backups.secret.name }}
  {{- end }}
data:
  ACCESS_KEY_ID: {{ required ".Values.backups.s3.accessKey is required, but not specified." .Values.backups.s3.accessKey | b64enc | quote }}
  ACCESS_SECRET_KEY: {{ required ".Values.backups.s3.secretKey is required, but not specified." .Values.backups.s3.secretKey | b64enc | quote }}
{{- end }}
